import { NextResponse } from "next/server";

import { MINIAPP_MANIFEST_CONFIG } from "@/lib/appConfig";

export const dynamic = "force-dynamic";

function parseAccountAssociation() {
  const raw = process.env.FARCASTER_ACCOUNT_ASSOCIATION_JSON;
  if (!raw) {
    return null;
  }

  try {
    const association = JSON.parse(raw);
    if (
      typeof association?.header === "string" &&
      typeof association?.payload === "string" &&
      typeof association?.signature === "string"
    ) {
      return association;
    }
  } catch {
    return null;
  }

  return null;
}

export function GET() {
  const accountAssociation = parseAccountAssociation();

  if (!accountAssociation) {
    return NextResponse.json(
      {
        error: "Missing signed Farcaster account association.",
        message:
          "Set FARCASTER_ACCOUNT_ASSOCIATION_JSON to the signed accountAssociation object generated by Farcaster Developer Tools for this exact production domain.",
      },
      { status: 404 },
    );
  }

  return NextResponse.json({
    accountAssociation,
    miniapp: MINIAPP_MANIFEST_CONFIG,
  });
}
